test

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,25 +1,25 @@
 #!/bin/sh
 git diff --cached --name-status | while read st file; do
-	# #
-	# # Skip deleted files
-	# # 
-	# if [ "$st" = 'D' ]; then continue; fi
+	#
+	# Skip deleted files
+	# 
+	if [ "$st" = 'D' ]; then continue; fi
 
-	# #
-	# # Path to the repository
-	# #
-	# dirpath=$(git rev-parse --show-toplevel)
-	# echo "File Name: " $file
+	#
+	# Path to the repository
+	#
+	dirpath=$(git rev-parse --show-toplevel)
+	echo "File Name: " $file
 
-	# go run "./.githooks/pre-commit.go" "./$file"
+	go run "./.githooks/pre-commit.go" "./$file"
 
-	# echo "go run "$dirpath/.githooks/pre-commit.go" $fileName"
+	echo "go run "$dirpath/.githooks/pre-commit.go" $fileName"
 
-	# if [ $? -gt 0 ]; then
-	# 	echo "Security check failed"
-	# 	git diff $file
-	# 	exit 1
-	# fi
+	if [ $? -gt 0 ]; then
+		echo "Security check failed"
+		git diff $file
+		exit 1
+	fi
 	exit 0
 done
 
